#!/usr/bin/ruby
#
# This file is part of CPEE-LIGHT.
#
# CPEE-INSTANTIATION is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# CPEE-LIGHT is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# CPEE-LIGHT (file LICENSE in the main directory).  If not, see
# <http://www.gnu.org/licenses/>.

require 'rubygems'
if File.exist?(File.join(__dir__,'..','lib','cpee-light','implementation.rb'))
  require_relative File.join(__dir__,'..','lib','cpee-light','implementation')
elsif File.exist?(File.join(Dir.home,'Projects','cpee-light','lib','cpee-light','implementation.rb'))
  require_relative File.join(Dir.home, 'Projects','cpee-light','lib','cpee-light','implementation')
else
  require 'cpee-light/implementation'
end

options = {
  :host => 'localhost',
  :port => 9326,
  :secure => false
}

Riddl::Server.new(CPEE::Light::SERVER, options) do
  accessible_description true
  cross_site_xhr true

  use CPEE::Light::implementation(@riddl_opts)
end.loop!
